server:
  port: 1212

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password: Admin1234$
  application:
    name: JWT
  jpa:
    hibernate:
      ddl-auto: update
